---
all:
  children:
    kubernetes:
      children:
        control_plane:
          children:
            primary:
              hosts:
                k8s01.turbo.local:
                  ansible_host: 192.168.86.241
                  control_plane_ip: 192.168.86.241
            backups:
              hosts:
                k8s02.turbo.local:
                  ansible_host: 192.168.86.242
                  control_plane_ip: 192.168.86.242
                k8s03.turbo.local:
                  ansible_host: 192.168.86.243
                  control_plane_ip: 192.168.86.243
