---

- name: Render kubeadm join
  ansible.builtin.template:
    src: templates/kubeadm_join.sh.j2
    dest: /etc/kubernetes/join.sh
    owner: root
    group: root
    mode: "0755"

- name: Kubeadm join via script
  ansible.builtin.command:
    cmd: /etc/kubernetes/join.sh
    creates: /etc/kubernetes/admin.conf
