---

- name: Render kubeadm init
  ansible.builtin.template:
    src: templates/kubeadm_init.sh.j2
    dest: /etc/kubernetes/init.sh
    owner: root
    group: root
    mode: "0755"

- name: Kubeadm init via script
  ansible.builtin.command:
    cmd: /etc/kubernetes/init.sh
    creates: /etc/kubernetes/admin.conf

- name: Create join command
  ansible.builtin.command:
    cmd: kubeadm token create --ttl 1h --print-join-command
  register: join_cmd

## XXX: install CNI
