---
# tasks file for k8s_control_plane

- name: Load modules
  ansible.builtin.include_tasks: tasks/systemd_load_module.yml
  vars:
    module: "{{ item }}"
    persistent: true
  loop:
    - br_netfilter
    - overlay

- name: Kernel Settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: true
    state: present
    reload: true
  loop:
    - { name: net.ipv4.ip_forward, value: '1' }
    - { name: net.bridge.bridge-nf-call-iptables, value: '1' }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: '1' }
