- name: CRI-O
  hosts: control_plane
  gather_facts: true
  gather_subset:
    - min
  tags:
    - crio
  vars:
    crio_pv: /dev/sdb
    crio_vg: k8s
    crio_lv: var_lib_containers
  tasks:
    - name: Create volume group
      community.general.lvg:
        state: present
        pvs:
          - "{{ crio_pv }}"
        vg: "{{ crio_vg }}"

    - name: Create logical volume
      community.general.lvol:
        state: present
        vg: "{{ crio_vg }}"
        lv: "{{ crio_lv }}"
        size: 50g
        shrink: false

    - name: Create filesystem
      community.general.filesystem:
        state: present
        dev: "/dev/{{ crio_vg }}/{{ crio_lv }}"
        fstype: xfs
        resizefs: true

    - name: Create mount directory
      ansible.builtin.file:
        state: directory
        path: /var/lib/containers
        owner: root
        group: root
        mode: "0755"

    - name: Mount filesystem
      ansible.posix.mount:
        state: mounted
        fstype: xfs
        opts: nodev,nosuid
        path: /var/lib/containers
        src: "/dev/{{ crio_vg }}/{{ crio_lv }}"

    # https://github.com/ansible/ansible/issues/64852#issuecomment-760454213
    - name: Enable CRIO dnf module
      ansible.builtin.copy:
        owner: root
        group: root
        mode: "0644"
        dest: /etc/dnf/modules.d/cri-o.module
        content: |
          [cri-o]
          name=cri-o
          stream={{ k8s.version.major }}.{{ k8s.version.minor }}
          profiles=
          state=enabled

    - name: Install CRI-O package
      ansible.builtin.dnf:
        name: cri-o
        state: installed
      notify:
        - Restart crio

    - name: Create CNI directory
      ansible.builtin.file:
        state: directory
        path: /etc/cni/net.d
        owner: root
        group: root
        mode: "0755"

    - name: Create default CNI configuration
      ansible.builtin.copy:
        src: files/10-crio-bridge.conflist
        dest: /etc/cni/net.d/10-crio-bridge.conflist
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart crio

    - name: Start CRI-O service
      ansible.builtin.systemd:
        name: crio
        state: started
        enabled: true
        daemon_reload: true
      when: false
  handlers:
    - name: Restart crio
      ansible.builtin.systemd:
        name: crio
        state: restarted
