---

- name: OS Configuration
  ansible.builtin.import_playbook: os_setup.yml

- name: CRI-O Configuration
  ansible.builtin.import_playbook: crio.yml

- name: Kubernetes Configuration
  ansible.builtin.import_playbook: kubernetes.yml
