---

- name: OS Configuration
  ansible.builtin.import_playbook: os_setup.yml

- name: Kubernetes Control Plane
  hosts: control_plane
  tasks:
    - name: Kubernetes Control Plane
      ansible.builtin.import_role:
        name: schweikm.k8s_control_plane
