---

- name: Common Configuration
  ansible.builtin.import_playbook: common.yaml

- name: Kubernetes Control Plane
  hosts: control_plane
  tasks:
    - name: Kubernetes Control Plane
      ansible.builtin.import_role:
        name: schweikm.k8s_control_plane
