---

- name: Kubernetes
  hosts: all
  gather_facts: true
  gather_subset:
    - min
  tags:
    - k8s
  tasks:
    - name: Create etcd LV
      ansible.builtin.include_tasks: tasks/create_lv.yml
      vars:
        vg_name: "{{ crio_vg }}"
        lv_name: var_lib_etcd
        lv_size: 2g
        lv_mount_dir: /var/lib/etcd

    - name: Deliver RPM GPG KEY
      ansible.builtin.copy:
        src: files/RPM-GPG-KEY-kubernetes-2023
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-kubernetes-2023
        owner: root
        group: root
        mode: "0644"

    - name: Import RPM GPG KEY
      ansible.builtin.rpm_key:
        state: present
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-kubernetes-2023

    - name: Create kubernetes yum repo
      ansible.builtin.yum_repository:
        state: present
        name: Kubernetes
        description: Kubernetes
        baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ k8s.version.major }}.{{ k8s.version.minor }}/rpm/"
        enabled: true
        gpgcheck: true
        gpgkey:
          - 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-kubernetes-2023'
        owner: root
        group: root
        mode: "0644"

    - name: Install Kubernetes packages
      ansible.builtin.dnf:
        name:
          - "kubeadm-{{ k8s.version.major }}.{{ k8s.version.minor }}.{{ k8s.version.patch }}"
          - "kubectl-{{ k8s.version.major }}.{{ k8s.version.minor }}.{{ k8s.version.patch }}"
          - "kubelet-{{ k8s.version.major }}.{{ k8s.version.minor }}.{{ k8s.version.patch }}"
        state: installed

    - name: Start kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: true
        daemon_reload: true
