---

- name: OS Configuration
  hosts: all
  gather_facts: true
  gather_subset:
    - min
  tags:
    - os
  tasks:
    - name: SELinux
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.selinux
      vars:
        selinux_policy: targeted
        selinux_state: permissive

    - name: Chrony
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: 2.fedora.pool.ntp.org
            maxpoll: 10
            iburst: true
            pool: true
            prefer: true

    - name: Crypto policies
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.crypto_policies
      vars:
        crypto_policies_policy: DEFAULT:NO-SHA1
        crypto_policies_reload: true
        crypto_policies_reboot_ok: true

    - name: Firewalld
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.firewall
      vars:
        firewall_disable_conflicting_services: true
        firewall:
          - port: "{{ firewalld_ports }}"
            state: enabled

    - name: Gather service facts
      ansible.builtin.service_facts:

    # https://fedoraproject.org/wiki/Changes/SwapOnZRAM#How_can_it_be_disabled?
    - name: Disable ZRAM swap
      ansible.builtin.systemd:
        name: systemd-zram-setup@zram0
        state: stopped
        enabled: false
      when: "'systemd-zram-setup@zram0.service' in ansible_facts.services"

    - name: Remove ZRAM packages
      ansible.builtin.dnf:
        name:
          - zram-generator
          - zram-generator-defaults
        state: absent
        allowerasing: true
        autoremove: true
