---

- name: OS Configuration
  hosts: control_plane,workers
  gather_facts: true
  gather_subset:
    - min
  tags:
    - os
  tasks:
    - name: SELinux
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.selinux
      vars:
        selinux_policy: targeted
        selinux_state: permissive

    - name: Chrony
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: 2.fedora.pool.ntp.org
            maxpoll: 10
            iburst: true
            pool: true
            prefer: true

    - name: Crypto policies
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.crypto_policies
      vars:
        crypto_policies_policy: DEFAULT:NO-SHA1
        crypto_policies_reload: true
        crypto_policies_reboot_ok: true

    - name: Firewalld Kubernetes
      ansible.builtin.import_role:
        name: fedora.linux_system_roles.firewall
      vars:
        firewall_disable_conflicting_services: true
        firewall:
          - port: "{{ firewalld_ports }}"
            state: enabled
            zone: public
            source: "{{ pod_cidr }}"

    - name: Gather service facts
      ansible.builtin.service_facts:

    # https://fedoraproject.org/wiki/Changes/SwapOnZRAM#How_can_it_be_disabled?
    - name: Disable ZRAM swap
      ansible.builtin.systemd:
        name: systemd-zram-setup@zram0
        state: stopped
        enabled: false
      when: "'systemd-zram-setup@zram0.service' in ansible_facts.services"

    - name: Determine if swap is active
      ansible.builtin.command:
        cmd: swapon -s
      register: swapon
      changed_when: false

    - name: Turn off swap at runtime
      ansible.builtin.command:
        cmd: swapoff -a
      when: swapon.stdout_lines | length > 0
      changed_when: true

    - name: Determine if zram generator is enabled
      ansible.builtin.stat:
        path: /etc/systemd/zram-generator.conf
      register: zram_stat

    - name: Disable zram
      ansible.builtin.file:
        path: /etc/systemd/zram-generator.conf
        state: touch
        owner: root
        group: root
        mode: '0644'
      when: not zram_stat.stat.exists
